import type { AssetContributionSummary, CapitalTruthSummary, FreshnessMetadata, Holding, PendingOrder, PerformanceSummary, PortfolioSummary, SyncStatus, Transaction } from '@/lib/api'
import type { DashboardContract } from '../../shared/typescript/contracts'

export const fixedNow = new Date('2026-04-14T10:15:30Z')

export const trustedDashboardContract: DashboardContract = {
  as_of: '2026-04-14T10:00:00Z',
  current_total_value_usd: '59510.38',
  rolling_30d: {
    label: '30D',
    days: 30,
    start_at: '2026-03-15T10:00:00Z',
    end_at: '2026-04-14T10:00:00Z',
    starting_value_usd: '53000.00',
    ending_value_usd: '59510.38',
    external_contributions_usd: '2000.00',
    external_withdrawals_usd: '500.00',
    investment_gain_usd: '5010.38',
    confidence_state: 'trusted',
    reason_codes: [],
    visible: true,
  },
  lifetime: {
    gross_contributions_usd: '47000.00',
    gross_withdrawals_usd: '3000.00',
    net_capital_at_work_usd: '44000.00',
    lifetime_pnl_usd: '15510.38',
    return_pct: '35.250863636363636',
    confidence_state: 'trusted',
    reason_codes: [],
    visible: true,
  },
  confidence_state: 'trusted',
  reason_codes: [],
  blocked_metric_scopes: [],
  asset_type_distribution: [
    {
      asset_type: 'crypto',
      value_usd: '40000.00',
      percentage: '67.214706681019',
      percentage_state: 'visible',
      confidence_state: 'trusted',
      reason_codes: [],
    },
    {
      asset_type: 'cash',
      value_usd: '8500.00',
      percentage: '14.283222898926',
      percentage_state: 'visible',
      confidence_state: 'trusted',
      reason_codes: [],
    },
    {
      asset_type: 'stocks_etfs',
      value_usd: '11010.38',
      percentage: '18.502070420055',
      percentage_state: 'visible',
      confidence_state: 'trusted',
      reason_codes: [],
    },
  ],
  cash_reserve: {
    stablecoin_usd: '6000.00',
    broker_cash_usd: '2500.00',
    other_tracked_cash_usd: '0.00',
    total_usd: '8500.00',
    confidence_state: 'trusted',
    reason_codes: [],
  },
  holding_drivers: [
    {
      symbol: 'BTC',
      movement_usd: '3100.00',
      share_of_known_movement_pct: '61.871746776293',
      direction: 'positive',
      confidence_state: 'trusted',
      reason_codes: [],
      value_state: 'visible',
    },
    {
      symbol: 'AAPL',
      movement_usd: '-275.00',
      share_of_known_movement_pct: '5.488606653587',
      direction: 'negative',
      confidence_state: 'trusted',
      reason_codes: [],
      value_state: 'visible',
    },
  ],
  top_reconciliation_action: null,
}

export const severeBlockedDashboardContract: DashboardContract = {
  ...trustedDashboardContract,
  rolling_30d: {
    ...trustedDashboardContract.rolling_30d,
    investment_gain_usd: null,
    confidence_state: 'blocked',
    reason_codes: ['missing_cost_basis'],
    visible: false,
  },
  lifetime: {
    ...trustedDashboardContract.lifetime,
    lifetime_pnl_usd: null,
    return_pct: null,
    confidence_state: 'blocked',
    reason_codes: ['missing_cost_basis'],
    visible: false,
  },
  confidence_state: 'blocked',
  reason_codes: ['missing_cost_basis'],
  blocked_metric_scopes: [
    'lifetime_pnl',
    'period_performance',
    'asset_level_lifetime_pnl',
  ],
  holding_drivers: [
    {
      symbol: 'BTC',
      movement_usd: null,
      share_of_known_movement_pct: null,
      direction: 'unknown',
      confidence_state: 'blocked',
      reason_codes: ['missing_cost_basis'],
      value_state: 'hidden',
    },
  ],
  top_reconciliation_action: {
    task_id: 'task_btc_cost_basis',
    task_type: 'missing_cost_basis',
    status: 'open',
    severity: 'blocked',
    source: 'binance',
    asset_symbol: 'BTC',
    quantity: '0.02',
    amount_usd: '1200.00',
    occurred_at: '2026-04-09T10:00:00Z',
    evidence: {
      source_evidence_key: 'btc-sell',
      reasons: ['missing_cost_basis'],
    },
    candidate_actions: [
      { action: 'manual_cost_basis', effect: 'restore_asset_pnl' },
    ],
    affected_metric_scopes: [
      'lifetime_pnl',
      'period_performance',
      'asset_level_lifetime_pnl',
    ],
    created_at: '2026-04-09T10:00:00Z',
  },
}

const freshPrice: FreshnessMetadata = {
  source: 'live_price_provider',
  as_of: '2026-04-14T10:00:00+00:00',
  stale: false,
  degraded: false,
  fallback: false,
  warnings: [],
}

export const dashboardHoldings: Holding[] = [
  {
    symbol: 'BTC',
    asset_type: 'crypto',
    institution: 'binance',
    quantity: 0.75,
    avg_buy_price_usd: 50000,
    current_price_usd: 72000,
    current_value_usd: 54000,
    total_cost_usd: 37500,
    unrealized_pnl_usd: 16500,
    unrealized_pnl_pct: 44,
    freshness: freshPrice,
  },
  {
    symbol: 'AAPL',
    asset_type: 'equity',
    institution: 'fidelity',
    quantity: 12,
    avg_buy_price_usd: 160,
    current_price_usd: 195.12,
    current_value_usd: 2341.44,
    total_cost_usd: 1920,
    unrealized_pnl_usd: 421.44,
    unrealized_pnl_pct: 21.95,
    freshness: freshPrice,
  },
  {
    symbol: 'SGOV',
    asset_type: 'etf',
    institution: 'ibkr',
    quantity: 31.25,
    avg_buy_price_usd: 100,
    current_price_usd: 100.03,
    current_value_usd: 3125.94,
    total_cost_usd: 3125,
    unrealized_pnl_usd: 0.94,
    unrealized_pnl_pct: 0.03,
    freshness: freshPrice,
  },
]

export const dashboardTransactions: Transaction[] = [
  {
    id: 201,
    institution: 'binance',
    type: 'buy',
    asset: 'BTC',
    asset_type: 'crypto',
    quantity: 0.25,
    price_usd: 68000,
    total_usd: 17000,
    fee: 12.5,
    fee_currency: 'USDT',
    timestamp: '2026-04-03T15:30:00Z',
  },
  {
    id: 202,
    institution: 'fidelity',
    type: 'dividend',
    asset: 'AAPL',
    asset_type: 'equity',
    quantity: 1.92,
    price_usd: 0,
    total_usd: 23.04,
    fee: 0,
    fee_currency: 'USD',
    timestamp: '2026-04-06T13:15:00Z',
  },
  {
    id: 203,
    institution: 'ibkr',
    type: 'snapshot',
    asset: 'SGOV',
    asset_type: 'etf',
    quantity: 31.25,
    price_usd: 100.03,
    total_usd: 3125.94,
    fee: 0,
    fee_currency: 'USD',
    timestamp: '2026-04-08T09:00:00Z',
  },
]

export const dashboardSummary: PortfolioSummary = {
  total_value_usd: 59510.38,
  total_cost_usd: 42545,
  total_pnl_usd: 16965.38,
  total_pnl_pct: 39.87,
  holding_count: dashboardHoldings.length,
  by_asset_type: {
    crypto: 54000,
    equity: 2341.44,
    etf: 3125.94,
  },
  benchmarks: {
    spx_in_btc: 0.0078125,
    spx_in_gold: 0.2,
  },
  holdings: dashboardHoldings,
}

export const dashboardCapitalTruth: CapitalTruthSummary = {
  money_in_usd: 39000,
  money_out_usd: 0,
  net_capital_in_usd: 39000,
  current_value_usd: 32550.25,
  lifetime_pnl_usd: -6449.75,
  lifetime_return_pct: -16.537820512820515,
  current_value_source: 'latest_position_snapshot',
  warnings: ['2 unclassified transfers need review'],
  excluded_row_count: 1,
  unclassified_transfer_count: 2,
  capital_flow_audit: [],
}

export const dashboardPerformanceSummary: PerformanceSummary = {
  combined: {
    gross_deposits_usd: 6000,
    gross_withdrawals_usd: 250,
    net_invested_capital_usd: 5750,
    reward_income_usd: 120,
    fees_usd: 14.5,
    realized_pnl_usd: 910.22,
    unrealized_pnl_usd: 16055.16,
    total_pnl_usd: 16965.38,
    total_cost_usd: 42545,
    current_value_usd: 59510.38,
    xirr: 0.1842,
  },
  institutions: {
    binance: {
      net_invested_capital_usd: 2500,
      reward_income_usd: 120,
      fees_usd: 14.5,
      realized_pnl_usd: 510.22,
      unrealized_pnl_usd: 15869.78,
      total_pnl_usd: 16380,
      current_value_usd: 54000,
      xirr: 0.271,
    },
    xtb: {
      net_invested_capital_usd: 3250,
      reward_income_usd: 0,
      fees_usd: 0,
      realized_pnl_usd: 400,
      unrealized_pnl_usd: 185.38,
      total_pnl_usd: 585.38,
      current_value_usd: 5510.38,
      xirr: 0.0784,
    },
  },
  comparisons: {
    binance_vs_xtb: {
      total_pnl_delta_usd: 15794.62,
      net_invested_delta_usd: -750,
    },
  },
}

export const dashboardAssetContributions: AssetContributionSummary = {
  assets: [
    {
      symbol: 'BTC',
      asset_type: 'crypto',
      institution: 'binance',
      institutions: ['binance'],
      quantity: 0.75,
      total_cost_usd: 37500,
      current_value_usd: 54000,
      realized_pnl_usd: 510.22,
      unrealized_pnl_usd: 16500,
      reward_income_usd: 120,
      fees_usd: 14.5,
      net_lifetime_pnl_usd: 17115.72,
    },
    {
      symbol: 'AAPL',
      asset_type: 'equity',
      institution: 'xtb',
      institutions: ['xtb'],
      quantity: 12,
      total_cost_usd: 1920,
      current_value_usd: 2341.44,
      realized_pnl_usd: 400,
      unrealized_pnl_usd: 421.44,
      reward_income_usd: 23.04,
      fees_usd: 0,
      net_lifetime_pnl_usd: 844.48,
    },
    {
      symbol: 'LUNA',
      asset_type: 'crypto',
      institution: 'binance',
      institutions: ['binance'],
      quantity: 0,
      total_cost_usd: 5800,
      current_value_usd: 0,
      realized_pnl_usd: -5400,
      unrealized_pnl_usd: 0,
      reward_income_usd: 0,
      fees_usd: 18,
      net_lifetime_pnl_usd: -5418,
    },
    {
      symbol: 'ARKK',
      asset_type: 'etf',
      institution: 'xtb',
      institutions: ['xtb'],
      quantity: 4,
      total_cost_usd: 1200,
      current_value_usd: 800,
      realized_pnl_usd: -150,
      unrealized_pnl_usd: -250,
      reward_income_usd: 0,
      fees_usd: 4,
      net_lifetime_pnl_usd: -404,
    },
  ],
  totals: {
    current_value_usd: 57141.44,
    realized_pnl_usd: -4639.78,
    unrealized_pnl_usd: 16671.44,
    reward_income_usd: 143.04,
    fees_usd: 36.5,
    net_lifetime_pnl_usd: 12138.2,
  },
  sort: {
    sort_by: 'net_lifetime_pnl_usd',
    order: 'desc',
  },
}

export const dashboardPendingOrders: PendingOrder[] = [
  {
    institution: 'binance',
    symbol: 'BTC',
    external_order_id: 'ord-002',
    order_type: 'limit',
    status: 'open',
    side: 'buy',
    quantity: 0.25,
    limit_price: 64000,
    stop_price: null,
    placed_at: '2026-04-15T10:00:00+00:00',
  },
  {
    institution: 'xtb',
    symbol: 'AAPL',
    external_order_id: 'ord-101',
    order_type: 'stop',
    status: 'pending',
    side: 'sell',
    quantity: 5,
    limit_price: null,
    stop_price: 185,
    placed_at: null,
  },
]

export const dashboardSyncStatuses: SyncStatus[] = [
  {
    name: 'binance',
    last_sync_at: '2026-04-14T10:00:00+00:00',
    degraded: true,
    warning: 'withdraw_history: withdraw disabled',
    note: 'API delta sync currently covers deposits, withdrawals, convert, Simple Earn, and C2C/P2P only.',
  },
  {
    name: 'xtb',
    last_sync_at: '2026-04-13T22:30:00+00:00',
    degraded: false,
    warning: null,
    note: null,
  },
]
