# ruff: noqa: S608
"""
Add Timescale hypertables and continuous aggregates for portfolio time-series data.

Revision ID: platform_003_timeseries
Revises: backend_foundation_tables
Create Date: 2026-04-20
"""

import os
from collections.abc import Sequence

from alembic import op

revision: str = "platform_003_timeseries"
down_revision: str | None = "backend_foundation_tables"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PORTFOLIO_AGGREGATE_BUCKETS = {
    "hourly": "1 hour",
    "daily": "1 day",
    "weekly": "1 week",
    "monthly": "1 month",
}
POLICY_SCHEDULE_INTERVALS = {
    "hourly": "1 hour",
    "daily": "6 hours",
    "weekly": "1 day",
    "monthly": "1 day",
}


def _skip_continuous_aggregate_policies() -> bool:
    return os.environ.get("PORTFOLIO_TEST_SKIP_TIMESCALE_POLICIES") == "1"


def _ensure_composite_primary_key(table_name: str) -> None:
    op.execute(
        f"""
        DO $$
        DECLARE
            current_pk_columns text[];
        BEGIN
            SELECT array_agg(attribute.attname ORDER BY attribute.attnum)
            INTO current_pk_columns
            FROM pg_constraint constraint_def
            JOIN pg_class relation ON relation.oid = constraint_def.conrelid
            JOIN pg_namespace schema_def ON schema_def.oid = relation.relnamespace
            JOIN unnest(constraint_def.conkey) WITH ORDINALITY AS key(attnum, ordinal)
                ON TRUE
            JOIN pg_attribute attribute
                ON attribute.attrelid = relation.oid
                AND attribute.attnum = key.attnum
            WHERE schema_def.nspname = 'public'
              AND relation.relname = '{table_name}'
              AND constraint_def.contype = 'p';

            IF current_pk_columns IS DISTINCT FROM ARRAY['id', 'captured_at'] THEN
                EXECUTE format(
                    'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
                    '{table_name}',
                    '{table_name}_pkey'
                );
                EXECUTE format(
                    'ALTER TABLE %I ADD CONSTRAINT %I PRIMARY KEY (id, captured_at)',
                    '{table_name}',
                    '{table_name}_pkey'
                );
            END IF;
        END
        $$;
        """
    )


def _create_portfolio_snapshot_aggregate(resolution: str, bucket_width: str) -> None:
    op.execute(
        f"""
        CREATE MATERIALIZED VIEW portfolio_snapshots_{resolution}
        WITH (timescaledb.continuous) AS
        SELECT
            time_bucket(INTERVAL '{bucket_width}', captured_at) AS bucket_start,
            asset_id,
            last(current_value_usd, captured_at) AS current_value_usd,
            last(total_cost_usd, captured_at) AS total_cost_usd
        FROM position_snapshots
        GROUP BY bucket_start, asset_id
        WITH NO DATA
        """
    )
    op.execute(
        "ALTER MATERIALIZED VIEW "
        f"portfolio_snapshots_{resolution} "
        "SET (timescaledb.materialized_only = false)"
    )
    if _skip_continuous_aggregate_policies():
        return
    op.execute(
        "SELECT add_continuous_aggregate_policy("
        f"'portfolio_snapshots_{resolution}', "
        "start_offset => INTERVAL '10 years', "
        f"end_offset => INTERVAL '{bucket_width}', "
        f"schedule_interval => INTERVAL '{POLICY_SCHEDULE_INTERVALS[resolution]}', "
        "if_not_exists => TRUE)"
    )


def _create_benchmark_quote_aggregate(resolution: str, bucket_width: str) -> None:
    op.execute(
        f"""
        CREATE MATERIALIZED VIEW benchmark_quotes_{resolution}
        WITH (timescaledb.continuous) AS
        SELECT
            time_bucket(INTERVAL '{bucket_width}', captured_at) AS bucket_start,
            symbol,
            last(price_usd, captured_at) AS price_usd
        FROM benchmark_quotes
        GROUP BY bucket_start, symbol
        WITH NO DATA
        """
    )
    op.execute(
        "ALTER MATERIALIZED VIEW "
        f"benchmark_quotes_{resolution} "
        "SET (timescaledb.materialized_only = false)"
    )
    if _skip_continuous_aggregate_policies():
        return
    op.execute(
        "SELECT add_continuous_aggregate_policy("
        f"'benchmark_quotes_{resolution}', "
        "start_offset => INTERVAL '10 years', "
        f"end_offset => INTERVAL '{bucket_width}', "
        f"schedule_interval => INTERVAL '{POLICY_SCHEDULE_INTERVALS[resolution]}', "
        "if_not_exists => TRUE)"
    )


def _restore_plain_position_snapshots_table() -> None:
    op.execute(
        """
        CREATE TABLE position_snapshots_plain (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            asset_id BIGINT NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
            captured_at TIMESTAMPTZ NOT NULL,
            quantity NUMERIC(30, 10) NOT NULL,
            avg_buy_price_usd NUMERIC(20, 6),
            total_cost_usd NUMERIC(20, 6),
            current_price_usd NUMERIC(20, 6),
            current_value_usd NUMERIC(20, 6),
            unrealized_pnl_usd NUMERIC(20, 6),
            unrealized_pnl_pct NUMERIC(20, 10),
            CONSTRAINT uq_position_snapshots_plain_asset_id_captured_at
                UNIQUE (asset_id, captured_at)
        )
        """
    )
    op.execute(
        """
        INSERT INTO position_snapshots_plain (
            id,
            asset_id,
            captured_at,
            quantity,
            avg_buy_price_usd,
            total_cost_usd,
            current_price_usd,
            current_value_usd,
            unrealized_pnl_usd,
            unrealized_pnl_pct
        )
        SELECT
            id,
            asset_id,
            captured_at,
            quantity,
            avg_buy_price_usd,
            total_cost_usd,
            current_price_usd,
            current_value_usd,
            unrealized_pnl_usd,
            unrealized_pnl_pct
        FROM position_snapshots
        ORDER BY id
        """
    )
    op.execute("DROP TABLE position_snapshots")
    op.execute("ALTER TABLE position_snapshots_plain RENAME TO position_snapshots")
    op.execute(
        "CREATE INDEX ix_position_snapshots_captured_at "
        "ON position_snapshots (captured_at)"
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('position_snapshots', 'id'),
            COALESCE((SELECT MAX(id) FROM position_snapshots), 1),
            (SELECT COUNT(*) > 0 FROM position_snapshots)
        )
        """
    )


def _restore_plain_benchmark_quotes_table() -> None:
    op.execute(
        """
        CREATE TABLE benchmark_quotes_plain (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            symbol VARCHAR(20) NOT NULL,
            captured_at TIMESTAMPTZ NOT NULL,
            price_usd NUMERIC(20, 6) NOT NULL,
            CONSTRAINT uq_benchmark_quotes_plain_symbol_captured_at
                UNIQUE (symbol, captured_at)
        )
        """
    )
    op.execute(
        """
        INSERT INTO benchmark_quotes_plain (
            id,
            symbol,
            captured_at,
            price_usd
        )
        SELECT
            id,
            symbol,
            captured_at,
            price_usd
        FROM benchmark_quotes
        ORDER BY id
        """
    )
    op.execute("DROP TABLE benchmark_quotes")
    op.execute("ALTER TABLE benchmark_quotes_plain RENAME TO benchmark_quotes")
    op.execute(
        "CREATE INDEX ix_benchmark_quotes_captured_at ON benchmark_quotes (captured_at)"
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('benchmark_quotes', 'id'),
            COALESCE((SELECT MAX(id) FROM benchmark_quotes), 1),
            (SELECT COUNT(*) > 0 FROM benchmark_quotes)
        )
        """
    )


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    _ensure_composite_primary_key("position_snapshots")
    _ensure_composite_primary_key("benchmark_quotes")
    op.execute(
        "SELECT create_hypertable("
        "'position_snapshots', "
        "by_range('captured_at'), "
        "if_not_exists => TRUE, "
        "migrate_data => TRUE)"
    )
    op.execute(
        "SELECT create_hypertable("
        "'benchmark_quotes', "
        "by_range('captured_at'), "
        "if_not_exists => TRUE, "
        "migrate_data => TRUE)"
    )

    for resolution, bucket_width in PORTFOLIO_AGGREGATE_BUCKETS.items():
        _create_portfolio_snapshot_aggregate(resolution, bucket_width)
        _create_benchmark_quote_aggregate(resolution, bucket_width)


def downgrade() -> None:
    for resolution in reversed(tuple(PORTFOLIO_AGGREGATE_BUCKETS)):
        op.execute(
            "SELECT remove_continuous_aggregate_policy("
            f"'benchmark_quotes_{resolution}', if_exists => TRUE)"
        )
        op.execute(
            "SELECT remove_continuous_aggregate_policy("
            f"'portfolio_snapshots_{resolution}', if_exists => TRUE)"
        )
        op.execute(f"DROP MATERIALIZED VIEW IF EXISTS benchmark_quotes_{resolution}")
        op.execute(f"DROP MATERIALIZED VIEW IF EXISTS portfolio_snapshots_{resolution}")
    _restore_plain_benchmark_quotes_table()
    _restore_plain_position_snapshots_table()
